PokemonRuby/config/routes.rb
PokemonRuby::Application.routes.draw do
  get "welcome/new"
  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "sign_up" => "users#new", :as => "sign_up"
  get "/moves/forget" => "moves#forget", :as => "forget"

  root :to => "trainers#index"
  
  resources :users  

  resources :sessions

  resources :bags

  resources :moves

  resources :moves_pokemons

  resources :pokemons

  resources :trainers

  

end

PokemonRuby/app/models/trainer.rb
class Trainer < ActiveRecord::Base
	has_many	:pokemons
	has_one		:bag, dependent: :destroy
	validates :name, presence: true, uniqueness: true
	validates :city, presence: true
	validates :badges, 	presence: true,
						numericality: {
								only_integer: true,
								greater_than_or_equal_to: 0,
								less_than_or_equal_to: 8
						}

end

PokemonRuby/app/controllers/trainers_controller.rb
class TrainersController < ApplicationController
  before_action :set_trainer, only: [:show, :edit, :update, :destroy]
  before_action :check_login

  # GET /trainers
  # GET /trainers.json
  def index
    @trainers = Trainer.all
  end

  # GET /trainers/1
  # GET /trainers/1.json
  def show
  end

  # GET /trainers/new
  def new
    if @adm
      @trainer = Trainer.new
    else
      respond_to do |format|
        format.html { redirect_to trainers_path, notice: "Only the admin can create things." }
        format.json { head :no_content }
      end
    end
  end

  # GET /trainers/1/edit
  def edit
    if !@adm
      respond_to do |format|
        format.html { redirect_to @trainer, notice: "Only the admin can edit things." }
        format.json { head :no_content }
      end
    end
  end

  # POST /trainers
  # POST /trainers.json
  def create
    @trainer = Trainer.new(trainer_params)

    respond_to do |format|
      if @trainer.save
        format.html { redirect_to :controller => "bags", :action => "new", :id => @trainer.id }
        format.json { render action: 'show', status: :created, location: @trainer }
      else
        format.html { render action: 'new' }
        format.json { render json: @trainer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trainers/1
  # PATCH/PUT /trainers/1.json
  def update
    respond_to do |format|
      if @trainer.update(trainer_params)
        format.html { redirect_to @trainer, notice: 'Trainer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @trainer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trainers/1
  # DELETE /trainers/1.json
  def destroy
    if @adm
      @trainer.pokemons.clear
      @trainer.destroy
      respond_to do |format|
        format.html { redirect_to trainers_url }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { redirect_to root_url, notice: "Only the admin can destroy things." }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trainer
      @trainer = Trainer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def trainer_params
      params.require(:trainer).permit(:name, :city, :badges)
    end

end

PokemonRuby/app/helpers/trainers_helper.rb
module TrainersHelper
end

PokemonRuby/app/views/trainers/_form.html.erb
<%= form_for(@trainer) do |f| %>
  <% if @trainer.errors.any? %>
    <div>  
      <% for message in @trainer.errors.full_messages %>  
        <span class="error_text"><%= message %></span><br />
      <% end %>  
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Name" %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label "City" %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label "Badges" %><br>
    <%= f.number_field :badges %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

PokemonRuby/app/views/trainers/edit.html.erb
<h1>Editing trainer</h1>

<%= render 'form' %>

<%= link_to 'Show', @trainer, class: "link" %> |
<%= link_to 'Back', trainers_path, class: "link" %>

PokemonRuby/app/views/trainers/index.html.erb
<h1>Listing trainers</h1>
<% if @trainers.length > 0 %>
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>City</th>
        <th>Badges</th>
      </tr>
    </thead>

    <tbody>
      <% @trainers.each do |trainer| %>
        <tr>
          <td><%= trainer.name %></td>
          <td><%= trainer.city %></td>
          <td><%= trainer.badges %></td>
          <td><%= link_to 'Show', trainer, class: "link"%></td>
          <% if @adm %>
            <td><%= link_to 'Edit', edit_trainer_path(trainer), class: "link"%></td>
            <td><%= link_to 'Destroy', trainer, method: :delete, data: { confirm: 'Are you sure?' }, class: "link"%></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <h2>There's no trainers to show</h2>
<% end %>
<br>


<%= link_to 'New Trainer', new_trainer_path, class: "link" %>

PokemonRuby/app/views/trainers/new.html.erb
<h1>New Trainer</h1>

<%= render 'form' %>

<button ><%= link_to 'Back', trainers_path, class: "link" %></button>

PokemonRuby/app/views/trainers/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @trainer.name %>
</p>

<p>
  <strong>City:</strong>
  <%= @trainer.city %>
</p>

<p>
  <strong>Badges:</strong>
  <%= @trainer.badges %>
</p>

<p>
  <strong>Bag:</strong>
  <% mochila = Bag.where(:trainer_id => @trainer.id) %>
  <% if mochila.length>0 %>
  	Pokeballs: <%= mochila.first.pokeballs %>, 
  	Potions: <%= mochila.first.potions %>.
    <%= link_to "Edit", edit_bag_path(@trainer.bag), class: "link" %>
  <% else %>
  	Empty
  <% end %>
</p>

<p>
  <strong>Pokemons:</strong>
  <% pokemons = @trainer.pokemons %>
  <% if pokemons.length>0 %>
		<% pokemons.each do |p| %>
			<p><%= link_to p.name, p, class: "link" %></p>
		<% end %>
	<% else %>
		None
	<% end %>
</p>

<%= link_to 'Edit', edit_trainer_path(@trainer), class: "link" %> |
<%= link_to 'Back', trainers_path, class: "link" %>