PokemonRuby/config/routes.rb
PokemonRuby::Application.routes.draw do
  get "welcome/new"
  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "sign_up" => "users#new", :as => "sign_up"
  get "/moves/forget" => "moves#forget", :as => "forget"

  root :to => "trainers#index"
  
  resources :users  

  resources :sessions

  resources :bags

  resources :moves

  resources :moves_pokemons

  resources :pokemons

  resources :trainers

  

end

PokemonRuby/app/models/bag.rb
class Bag < ActiveRecord::Base
	belongs_to :trainer
end

PokemonRuby/app/controllers/bags_controller.rb
class BagsController < ApplicationController
  before_action :set_bag, only: [:show, :edit, :update, :destroy]
  before_action :check_login
  before_action :notshow, only: [:index]

  # GET /bags
  # GET /bags.json
  def index
    @bags = Bag.all
  end

  # GET /bags/1
  # GET /bags/1.json
  def show
  end

  # GET /bags/new
  def new
    if @adm
      @bag = Bag.new
    else
      respond_to do |format|
        format.html { redirect_to root_url, notice: "Only the admin can create things." }
        format.json { head :no_content }
      end
    end
  end

  # GET /bags/1/edit
  def edit
    if !@adm
      respond_to do |format|
        format.html { redirect_to @bag.trainer, notice: "Only the admin can edit things." }
        format.json { head :no_content }
      end
    end
  end

  # POST /bags
  # POST /bags.json
  def create
    @bag = Bag.new(bag_params)

    if @bag.save
      if params[:trainer_id] != nil
        @trainer=Trainer.find(params[:trainer_id])
        if @trainer.bag.nil?
          @trainer.bag = @bag
          @trainer.save
          respond_to do |format|
            format.html { redirect_to @trainer, notice: 'Trainer successfully created.' }
            format.json { render action: 'show', status: :created, location: @bag }
          end
        else
          respond_to do |format|
            format.html { redirect_to root_url, notice: 'This trainer already has a bag.' }
          end
        end
      else
        respond_to do |format|
          format.html { redirect_to @bag, notice: 'Bag was successfully created.' }
          format.json { render action: 'show', status: :created, location: @bag }
        end
      end
    else
      respond_to do |format|
        format.html { render action: 'new' }
        format.json { render json: @bag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bags/1
  # PATCH/PUT /bags/1.json
  def update
    respond_to do |format|
      if @bag.update(bag_params)
        format.html { redirect_to @bag, notice: 'Bag was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @bag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bags/1
  # DELETE /bags/1.json
  def destroy
    @bag.destroy
    if @adm
      respond_to do |format|
        format.html { redirect_to bags_url }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { redirect_to root_url, notice: "Only the admin can destroy things." }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bag
      @bag = Bag.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bag_params
      params.require(:bag).permit(:pokeballs, :potions, :trainer_id)
    end
end

PokemonRuby/app/helpers/bags_helper.rb
module BagsHelper
end

PokemonRuby/app/views/bags/_form.html.erb
<%= form_for(@bag) do |f| %>
  <% if @bag.errors.any? %>
    <div>  
      <% for message in @bag.errors.full_messages %>  
        <span class="error_text"><%= message %></span><br />
      <% end %>  
    </div>
  <% end %>

  <div class="field">
    <%= f.label :pokeballs %><br>
    <%= f.number_field :pokeballs %>
  </div>
  <div class="field">
    <%= f.label :potions %><br>
    <%= f.number_field :potions %>
  </div>
  <% if @trainer != nil %>
    <input type="hidden" name="trainer_id" value="<%= @trainer.id %>" />
  <% end %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

PokemonRuby/app/views/bags/edit.html.erb
<h1>Editing bag</h1>

<%= render 'form' %>

<%= link_to 'Show', @bag, class: "link" %> |
<%= link_to 'Back', bags_path, class: "link" %>

PokemonRuby/app/views/bags/index.html.erb
<h1>Listing bags</h1>
<% if @bags.length > 0 %>
  <table>
    <thead>
      <tr>
        <th>Pokeballs</th>
        <th>Potions</th>
        <th>Trainer</th>
      </tr>
    </thead>

    <tbody>
      <% @bags.each do |bag| %>
        <tr>
          <td><%= bag.pokeballs %></td>
          <td><%= bag.potions %></td>
          <td><%= bag.trainer.name %></td>
          <td><%= link_to 'Show', bag %></td>
          <% if @adm %>
            <td><%= link_to 'Edit', edit_bag_path(bag) %></td>
            <td><%= link_to 'Destroy', bag, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <h2>There's no bags to show</h2>
<% end %>
<br>

<%= link_to 'New Bag', new_bag_path, class: "link" %>

PokemonRuby/app/views/bags/new.html.erb
<% if params[:id].nil? %>
	<h1>New bag</h1>
<% else %>
	<% @trainer=Trainer.find(params[:id]) %>
	<h1>New bag for <%= @trainer.name %> </h1>
<% end %>

<%= render 'form' %>

<%= link_to 'Back', bags_path, class: "link" %>

PokemonRuby/app/views/bags/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Pokeballs:</strong>
  <%= @bag.pokeballs %>
</p>

<p>
  <strong>Potions:</strong>
  <%= @bag.potions %>
</p>

<p>
  <strong>Trainer:</strong>
  <%= @bag.trainer.name %>
</p>

<%= link_to 'Edit', edit_bag_path(@bag), class: "link" %> |
<%= link_to 'Back', bags_path, class: "link" %>