PokemonRuby/config/routes.rb
PokemonRuby::Application.routes.draw do
  get "welcome/new"
  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "sign_up" => "users#new", :as => "sign_up"
  get "/moves/forget" => "moves#forget", :as => "forget"

  root :to => "trainers#index"
  
  resources :users  

  resources :sessions

  resources :bags

  resources :moves

  resources :moves_pokemons

  resources :pokemons

  resources :trainers

  

end

PokemonRuby/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PokemonRuby</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<!-- <header></header> -->
	<nav id="user_nav">
		<% if current_user %>
			<span id="loggedin">
				Logged in as <br /><strong><%= current_user.login %></strong><br>
			</span>
			<%= link_to (log_out_path) do %>
				<span class="logbutton" id="logout" onclick="location.href='<%= log_out_path %>';" > Log out </span>
			<% end %>
			<% if session[:user_id]==1  %>
				<%= link_to (users_path) do %>
					<span class="logbutton" id="users" onclick="location.href='<%= users_path %>';" > Manage Users </span>
				<% end %>
			<% end %>
		<% else %>
			<%= link_to (sign_up_path) do %>
				<span class="logbutton" id="signup" onclick="location.href='<%= sign_up_path %>';" > Sign up </span>
			<% end %>
			<%= link_to (log_in_path) do %>
				<span class="logbutton" id="login" onclick="location.href='<%= log_in_path %>';" > Log in </span>
			<% end %>
		<% end %>
		<%= link_to (moves_path) do %>
			<span class="navbutton" id="moves" onclick="location.href='<%= moves_path %>';" > Moves </span>
		<% end %>
		<%= link_to (trainers_path) do %>
			<span class="navbutton" id="trainers" onclick="location.href='<%= trainers_path %>';" > Trainers </span>
		<% end %>
		<%= link_to (pokemons_path) do %>
			<span class="navbutton" id="pokemons" onclick="location.href='<%= pokemons_path %>';" > Pokemons </span>
		<% end %>
		<span class="flashmsg">
			<% flash.each do |name, msg| %>
				<%= content_tag :div, msg, :id => "flash#{name}" %>
			<% end %>
		</span>
	</nav>
<div class="mainframe"><%= yield %></div>

</body>
</html>