PokemonRuby/config/routes.rb
PokemonRuby::Application.routes.draw do
  get "welcome/new"
  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "sign_up" => "users#new", :as => "sign_up"
  get "/moves/forget" => "moves#forget", :as => "forget"

  root :to => "trainers#index"
  
  resources :users  

  resources :sessions

  resources :bags

  resources :moves

  resources :moves_pokemons

  resources :pokemons

  resources :trainers

  

end

PokemonRuby/app/models/pokemon.rb
class Pokemon < ActiveRecord::Base
	belongs_to	:trainer
	has_and_belongs_to_many	:moves

	validates	:name, 	presence: true
	validates	:pokedex_number, presence: true, 
								 numericality: {
										only_integer: true,
										greater_than_or_equal_to: 1,
										less_than_or_equal_to: 386
								 }
	validates	:poketype, 	presence: true
end

PokemonRuby/app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController
  before_action :set_pokemon, only: [:show, :edit, :update, :destroy]
  before_action :check_login

  # GET /pokemons
  # GET /pokemons.json
  def index
    @pokemons = Pokemon.all
  end

  # GET /pokemons/1
  # GET /pokemons/1.json
  def show
    pokemon=Pokemon.find(params[:id])
    File.open(Rails.root.join("public","pokedex.txt"), "r") { |file|
      file.each_line do |line|
        name=line.split('-').first
        if name==pokemon.name.downcase
          pokedex=line.split('-')[1].to_s.chomp
          pokedex="0"*(3-pokedex.length)+pokedex
          @imgurl="http://assets22.pokemon.com/assets/cms2/img/pokedex/full/"+pokedex+".png"
          break;
        end
      end
    }
  end

  # GET /pokemons/new
  def new
    if @adm
      @pokemon = Pokemon.new
      @trainers = Trainer.all
    else
      respond_to do |format|
        format.html { redirect_to pokemons_path, notice: "Only the admin can create things." }
        format.json { head :no_content }
      end
    end
  end

  # GET /pokemons/1/edit
  def edit
    if @adm
      @trainers = Trainer.all
    else
      respond_to do |format|
        format.html { redirect_to @pokemon, notice: "Only the admin can edit things." }
        format.json { head :no_content }
      end
    end
  end

  # POST /pokemons
  # POST /pokemons.json
  def create
    @pokemon = Pokemon.new(pokemon_params)
    @pokemon.n_moves=0
    respond_to do |format|
      if @pokemon.save
        format.html { redirect_to :controller => "moves", :action => "new", :id => @pokemon.id }
        format.json { render action: 'show', status: :created, location: @pokemon }
      else
        format.html { render action: 'new' }
        format.json { render json: @pokemon.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pokemons/1
  # PATCH/PUT /pokemons/1.json
  def update
    respond_to do |format|
      if @pokemon.update(pokemon_params)
        format.html { redirect_to :controller => "moves", :action => "new", :id => @pokemon.id }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @pokemon.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pokemons/1
  # DELETE /pokemons/1.json
  def destroy
    if @adm
      @pokemon.moves.clear
      @pokemon.destroy
      respond_to do |format|
        format.html { redirect_to pokemons_url }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { redirect_to root_url, notice: "Only the admin can destroy things." }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pokemon
      @pokemon = Pokemon.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pokemon_params
      params.require(:pokemon).permit(:name, :pokedex_number, :poketype, :n_moves, :trainer_id)
    end
end

PokemonRuby/app/helpers/pokemons_helper.rb
module PokemonsHelper
end

PokemonRuby/app/views/pokemons/_form.html.erb
<%= form_for(@pokemon) do |f| %>
  <% if @pokemon.errors.any? %>
    <div>  
      <% for message in @pokemon.errors.full_messages %>  
        <span class="error_text"><%= message %></span><br />
      <% end %>
    </div>
    <% @trainers=Trainer.all %>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label "Pokedex number" %><br>
    <%= f.number_field :pokedex_number %>
  </div>
  <div class="field">
    <%= f.label "Type" %><br>
    <%= f.select :poketype, ["Normal","Fire","Fighting","Water","Flying","Grass","Poison","Electric","Ground","Psychic","Rock","Ice","Bug","Dragon","Ghost","Dark","Steel"] %>
  </div>
  <div class="field">
    <%= f.label :trainer_id %><br>
    <% options = options_from_collection_for_select(@trainers, 'id', 'name') %>
    <%= f.collection_select :trainer_id, @trainers, :id, :name, {:include_blank => 'Empty (wild)'} %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

PokemonRuby/app/views/pokemons/edit.html.erb
<h1>Editing pokemon</h1>

<%= render 'form' %>

<%= link_to 'Show', @pokemon, class: "link" %> |
<%= link_to 'Back', pokemons_path, class: "link" %>

PokemonRuby/app/views/pokemons/index.html.erb
<h1>Listing pokemons</h1>
<% if @pokemons.length > 0 %>
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Pokedex number</th>
        <th>Type</th>
        <th>Number of moves</th>
        <th>Owner trainer</th>
      </tr>
    </thead>

    <tbody>
      <% @pokemons.each do |pokemon| %>
        <tr>
          <td><%= pokemon.name %></td>
          <td><%= pokemon.pokedex_number %></td>
          <td><%= pokemon.poketype %></td>
          <td><%= pokemon.n_moves %></td>
          <% if pokemon.trainer != nil%>
            <td><%= pokemon.trainer.name %></td>
          <% else %>
            <td><%= "None(Wild)" %></td>
          <% end %>
          <td><%= link_to 'Show', pokemon, class: "link" %></td>
          <% if @adm %>
            <td><%= link_to 'Edit', edit_pokemon_path(pokemon), class: "link" %></td>
            <td><%= link_to 'Destroy', pokemon, method: :delete, data: { confirm: 'Are you sure?' }, class: "link" %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <h2>There's no pokemons to show</h2>
<% end %>

<br>

<%= link_to 'New Pokemon', new_pokemon_path, class: "link" %> | 
<%= link_to 'Teach Moves', new_moves_pokemon_path, class: "link" %>

PokemonRuby/app/views/pokemons/new.html.erb
<h1>New pokemon</h1>

<%= render 'form' %>

<%= link_to 'Back', pokemons_path, class: "link" %>

PokemonRuby/app/views/pokemons/show.html.erb
<% if @imgurl != nil %>
  <%= image_tag @imgurl, class: "pokemon" %>
<% end %>
<p>
  <strong>Name:</strong>
  <%= @pokemon.name %>
</p>

<p>
  <strong>Pokedex number:</strong>
  <%= @pokemon.pokedex_number %>
</p>

<p>
  <strong>Type:</strong>
  <%= @pokemon.poketype %>
</p>

<p>
  <strong>Moves:</strong>
  <% if @pokemon.moves.length == 0 %>
    None
  <% else %>
    <% @pokemon.moves.each do |move| %>
      <br /> <%= link_to move.name, move, class: "link" %>
      <% if @adm %>
        - <%= link_to "Forget", controller: :moves, action: :forget, pokemon_id: @pokemon.id, move_id: move.id, data: { confirm: 'Are you sure?' }, class: "link" %>
      <% end %>
    <% end %>
  <% end %>
</p>

<p>
  <strong>Trainer:</strong>
  <% if @pokemon.trainer.nil? %>
    None (Wild Pokemon)
  <% else %>
    <%= link_to @pokemon.trainer.name, @pokemon.trainer, class: "link" %>
  <% end %>
</p>

<%= link_to 'Edit', edit_pokemon_path(@pokemon), class: "link" %> |
<%= link_to 'Back', pokemons_path, class: "link" %>